### ISSUE TITLE
brotli 1.0.1

### ISSUE THREAD

**Issue by felixonmars** [python-hyper/brotlipy#129]
Will there be an update for brotlipy soon? There's brotli version 1.0.0 and 1.0.1.

**Comment by thedrow** [comment]
Now on 1.0.7.

**Comment by rathann** [comment]
Starting from 1.0.0, the support for custom dictionaries was removed, so at a minimum, there needs to be a version check and ifdefs around each use of `BrotliEncoderSetCustomDictionary` and `BrotliDecoderSetCustomDictionary`.

**Comment by sethmlarson** [comment]
We're going to update to 1.0.7.
