### ISSUE TITLE
conflicting module name with google brotli python bindings

### ISSUE THREAD

**Issue by rathann** [python-hyper/brotlipy#145]
This project is named `brotlipy` but the python module provided is named `brotli`, same as Google's `brotli` python bindings. This makes it impossible to have both installed at the same time. Please rename the python module to `brotlipy`.

**Comment by jayvdb** [comment]
Or maybe rename to [brotlicffi](https://pypi.org/project/brotlicffi/) currently available, and would help to explain the difference.

**Comment by sethmlarson** [comment]
I'm in favor of using `brotlicffi` as the name of the package. My proposal is for v0.8.0 both `brotlipy` and `brotlicffi` will be published. `brotlipy` users will receive an import `DeprecationWarning` about migrating to `brotlicffi` or installing Google's `brotli` package if they don't need CFFI. `brotlicffi` will use the `brotlicffi` namespace so there isn't a conflict any more.

Does this proposal seem good to others?
