### ISSUE TITLE
Linking against system libbroti

### ISSUE THREAD

**Issue by jayvdb** [python-hyper/brotlipy#149]
Would it be possible/acceptable to link against the system libbroti instead of adding another one.

This would be especially useful for distros wanting to have only one copy of each library, and where they have a preference for avoiding vendored code, due to licensing issues, etc.

I would be interesting in helping set up the setup.py voodoo to make it allow that an option.

**Comment by felixonmars** [comment]
The patch here may be a start point: https://git.archlinux.org/svntogit/community.git/tree/trunk/shared-brotli.patch?h=packages/python-brotlipy

(That's how we are currently using for Arch Linux.)

**Comment by jayvdb** [comment]
Thanks @felixonmars .  I see that patch is already merged, but not released.
Submitted the patch to openSUSE https://build.opensuse.org/request/show/744825
