### ISSUE TITLE
Wheel for Python 3.7 Plz

### ISSUE THREAD

**Issue by shmilylty** [python-hyper/brotlipy#153]
OS: Windows 10 x64
Python: 3.7.4 x64

CMD: pipenv install  brotlipy

alway give me:
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

But I have installed Microsoft Visual C++ 14.0:

![image](https://user-images.githubusercontent.com/24275308/62802800-61c01480-bb1b-11e9-8962-0f3d9ce8958c.png)

@python-hyper @thedrow @Lukasa

More detail:

Installing collected packages: brotlipy
  Running setup.py install for brotlipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kdxpwtlq\\brotlipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kdxpwtlq\\brotlipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shmily\AppData\Local\Temp\pip-record-udsyn246\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\shmily\AppData\Local\Temp\pip-install-kdxpwtlq\brotlipy\
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\brotli
    copying src\brotli\brotli.py -> build\lib.win-amd64-3.7\brotli
    copying src\brotli\build.py -> build\lib.win-amd64-3.7\brotli
    copying src\brotli\__init__.py -> build\lib.win-amd64-3.7\brotli
    warning: build_py: byte-compiling is disabled, skipping.

    running build_clib
    building 'libbrotli' library
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kdxpwtlq\\brotlipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\shmily\\AppData\\Local\\Temp\\pip-install-kdxpwtlq\\brotlipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shmily\AppData\Local\Temp\pip-record-udsyn246\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by sethmlarson** [comment]
I'll need to setup my Windows machine to build the wheel. Can you ping this issue in a week?

**Comment by shmilylty** [comment]
Many people have encountered this problem, and it is recommended that provide a whl file for python 3.7.

**Comment by shmilylty** [comment]
@sethmlarson How is it going, please?

**Comment by sethmlarson** [comment]
I'm taking a look at cibuildwheel and seeing if I can get it setup for this project. It's a hassle to build wheels for all platforms for all versions. :)

**Comment by shmilylty** [comment]
Waiting for your good news : P

**Comment by sethmlarson** [comment]
I've uploaded Python 3.7 wheels for Windows and macOS.

**Comment by shmilylty** [comment]
Thx a lot！
