### ISSUE TITLE
Clarify API provenance

### ISSUE THREAD

**Issue by jason-sachs** [python-hyper/brotlipy#163]
I was going to file an issue asking for an improvement in the API, but noticed that the intent seems to be compability with Google's python bindings.

Could you clarify this in the documentation? Which classes/methods are meant to mirror the Google bindings, and which (if any) are different?

**Comment by sethmlarson** [comment]
We're now clarifying 100% compatibility with Google's C bindings for specifically the `brotlicffi` package.
