### ISSUE TITLE
Is 2.7 supported on Windows?

### ISSUE THREAD

**Issue by ionelmc** [python-hyper/brotlipy#17]
I seem to get this mindboggling error: https://gist.github.com/ionelmc/746e53d0cfd3ed5f2a321f64e2d4896e

I'd use Py3 (which don't have this problem) but I can't :confounded:

**Comment by Lukasa** [comment]
I have a *suspicion* that it's not: the brotli maintainers are a tricky bunch with weird attitudes about a lot of things, but the biggest problem is likely to be that to compile Python 2 extensions on Windows requires  using VS 2008. I seem to recall that myself and @reaperhulk discovered that that simply didn't work with libbrotli: they were relying on too many modern features.

This is rather disappointing, I know. =(

**Comment by ionelmc** [comment]
A warning or something about requirements in the readme would prevent people needlessly chasing this problem.

**Comment by Lukasa** [comment]
@ionelmc Good call. =)

**Comment by anthrotype** [comment]
the Brotli library can be compiled with Visual Studio 2008 and above with no problem, as you can see from the list of pre-compiled Python wheels in https://github.com/google/brotli/releases
(built automatically on Appveyor and Travis CI). 
The developers are not `a tricky bunch`. They have removed all advanced C++11 which were originally there specifically to allow compiling the extension module for old Windows pythons.

**Comment by Lukasa** [comment]
@anthrotype As of when, though? I haven't revved this in a little while, which is why I ran off that information: AFAIK, the information is valid for the SHA that is pinned in the submodule.
