### ISSUE TITLE
add support for `mode` and other kwargs in `compress` function

### ISSUE THREAD

**Issue by anthrotype** [python-hyper/brotlipy#35]
Hi, thanks for the great cffi wrapper!

It would be nice if the signature of the `compress` function could match the one from `brotlimodule.cc` at https://github.com/google/brotli/blob/master/python/brotlimodule.cc#L93
```
compress(string, mode=MODE_GENERIC, quality=11, lgwin=22, lgblock=0, dictionary='')
```

That would allow me to drop in `brotlipy` as a replacement for google/brotli CPython bindings.

Cheers,

Cosimo

**Comment by Lukasa** [comment]
This is a great idea. I'll tackle this after the move to brotli 0.5.1, which should let me throw away my C-based wrapper for the C++ based encoder.

**Comment by Lukasa** [comment]
So, after #36 is merged we can look to extend the API to add all those flags. =)

**Comment by anthrotype** [comment]
great, thanks!
