### ISSUE TITLE
BROTLI_MODE_* constants are named differently in _brotlimodule.cc 

### ISSUE THREAD

**Issue by anthrotype** [python-hyper/brotlipy#39]
Would it be possible to add `MODE_GENERIC`, `MODE_TEXT` and `MODE_FONT` to brotlipy?
Or do you think those should be renamed in the upstream bindings?

See https://github.com/google/brotli/blob/master/python/brotlimodule.cc#L296-L298

I use them like this:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/woff2.py#L217
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/woff2.py#L375

**Comment by Lukasa** [comment]
So they are currently present in `master`, but have different names:

`BrotliEncoderMode.BROTLI_MODE_GENERIC`, `BrotliEncoderMode.BROTLI_MODE_TEXT`, and `BrotliEncoderMode.BROTLI_MODE_FONT`. I can certainly rename them here.

**Comment by anthrotype** [comment]
that would be great, thanks!

**Comment by anthrotype** [comment]
superb! looking forward to the next pypi release :)

**Comment by Lukasa** [comment]
Ok, v0.5.0 has shipped, including wheels for Mac OS X, Windows, and Linux. =)

**Comment by anthrotype** [comment]
> including wheels for Mac OS X, Windows, and Linux. =)

this is great! Just curious, did you use Travis CI to build the OS X and manylinux1 wheels with something like https://github.com/matthew-brett/multibuild ?

**Comment by Lukasa** [comment]
I did not.

For OS X and Windows I use the same Jenkins build farm as the [pyca/cryptography](https://github.com/pyca/cryptography) folks, which they kindly lent me access to for this job. It's pretty minor: it just downloads the sdist and builds wheels from it, which I then download, sign, and upload.

For Linux I use a [collection of scripts and dockerfiles](https://github.com/python-hyper/brotlipy-manylinux1) that was forked from more work done by the cryptography folks (this time for building wheels for CFFI, which incidentally means that the CFFI-based brotlipy actually requires *no* compilation of any kind on 99% of systems). This uses docker on my local machine, along with the docker manylinux1 image, to build manylinux1 wheels from the sdist.

So far this is a pretty good workflow. Almost all of the work here is built on top of things that @reaperhulk initially did, which means I owe him a *huge* debt of gratitude, but it's really nice to be able to say that brotlipy and all its dependencies can be installed from wheels from PyPI.

**Comment by anthrotype** [comment]
indeed, that's the way forward 👍
