### ISSUE TITLE
AttributeError: module 'brotli' has no attribute 'error'

### ISSUE THREAD

**Issue by anthrotype** [python-hyper/brotlipy#43]
`_brotlimodule.cc` also exports a custom exception, simply called `error`:

https://github.com/google/brotli/blob/master/python/brotlimodule.cc#L289

it would be nice if brotlipy did the same (I need catch `brotli.error` in my test suite).

Thanks!

BTW: brotlipy is great!

**Comment by Lukasa** [comment]
@anthrotype Yeah, I can do that. I'll need to check the places it's raised as well.

I'll aim to get to this sometime this week, though I'm pretty slammed so I can't guarantee it yet. But I'm glad you're enjoying brotlipy!

**Comment by anthrotype** [comment]
Thanks. The exception is simply raised if the `compress` or `decompress` fail to return valid data (or get invalid arguments).

**Comment by Lukasa** [comment]
For what it's worth, in this case I'll define the exception in the same was as it's defined in brotlimodule.cc, but I will *also* give it a different name in the brotlipy source code that is in line with regular Python style. (Generally speaking, a Python exception is a class and so should have a CamelCase style name.)

**Comment by anthrotype** [comment]
definitely, I agree. Maybe that could be changed in the upstream too.

**Comment by Lukasa** [comment]
Certainly worth considering. I'll do this first and then offer a PR upstream.

**Comment by anthrotype** [comment]
sorry, one more thing. In the upstream brotli, if the `decompress` receives an empty byte string, it returns an error, whereas in `brotlipy` it returns an empty string `b""`.
I'm not sure which of the two behaviors should be the correct one...

```python
>>> from brotli import decompress
>>> decompress(b"")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
brotli.error: BrotliDecompress failed
```

**Comment by Lukasa** [comment]
@anthrotype Probably neither, to be honest. It seems like the correct thing to do would be to raise a `ValueError`. How important is the consistency here? Is this just affecting your test code?

**Comment by anthrotype** [comment]
yeah, I guess in this case I'll just change the test. ;)
