### ISSUE TITLE
decompress method should accept a dictionary parameter

### ISSUE THREAD

**Issue by bra-fsn** [python-hyper/brotlipy#57]
Hi,
It's very nice that the library supports specifying a custom dictionary to compress(), but it lacks the same option on decompress(), which makes it somewhat hard(er) to use.
Please provide a dictionary parameter to that method.

**Comment by KOLANICH** [comment]
damn, almost 3 years have passed.

**Comment by bra-fsn** [comment]
Time flies in good company :)

**Comment by sethmlarson** [comment]
No longer needed now that 1.0.7 has dropped the dictionary functionality.

**Comment by KOLANICH** [comment]
They have a separate branch with dictionaries. They have claimed they have dropped the API because they have have not imroved it enough to make it stable and keep forever.

**Comment by sethmlarson** [comment]
When the API is stable we can bring it back, I have no problem doing that. However if we build against the most recent Brotli libraries there is no dictionary functionality.
