### ISSUE TITLE
Include submodules in releases

### ISSUE THREAD

**Issue by theSoenke** [python-hyper/brotlipy#68]
It would be great if the tarball releases could contain the libbrotli submodule. Would make it easier to build it from the tarball and make it reproducible

Thanks

**Comment by sigmavirus24** [comment]
I'm pretty sure that's exactly what https://github.com/python-hyper/brotlipy/blob/03ec19d8d46383fe36bb0cc84fc74098d2401216/MANIFEST.in#L5..L10 should be doing. Which versions are you attempting to build from that don't have the libbrotli submodule?

**Comment by theSoenke** [comment]
I tried to build it from https://github.com/python-hyper/brotlipy/archive/v0.6.0.tar.gz and it does not contain the libbrotli subdirectory. The automatically generated github tarballs do no include submodules

**Comment by Lukasa** [comment]
Oh, I see: the problem is a GitHub one. Is the tarball from GitHub a git repo? If so, you can just checkout the submodules. If not, there is very little I can do without moving away from the submodule structure. 

I recommend using `pip download` to obtain an appropriate tarball to avoid this issue.

**Comment by sigmavirus24** [comment]
> The automatically generated github tarballs do no include submodules

Yeah, the thing is that we have no control over how those are generated. So sorry. You should use the source distributions from PyPI (as @Lukasa has suggested).

**Comment by theSoenke** [comment]
I did not realize that the PyPI release contains libbrotli. That works. Thanks
