### ISSUE TITLE
Wheel for Python 3.6

### ISSUE THREAD

**Issue by paskyorg** [python-hyper/brotlipy#69]
I'm trying to install brotlipy on my Windows 10 with Python 3.6, but it requires "Microsoft Visual C++ Build Tools" and need to download 4 GB. It would be possible to download a wheel version?

I have seen at https://pypi.python.org/pypi/brotlipy and there are only up to version 3.5.

Thanks!

**Comment by Lukasa** [comment]
Yup, this is definitely an oversight. I'll chat to the person who kindly maintains the wheel builder for me to see if they can give me access to a 3.6 build.

Thanks for the report!

**Comment by hubo1016** [comment]
I think what you need is the VC++ compiler only
https://www.visualstudio.com/downloads/#microsoft-visual-c-build-tools-2015-update-3
This is quite small

**Comment by Lukasa** [comment]
Ok, the Python 3.6 wheels are uploaded. Thanks for pointing this out, Python 3.6 will be part of the build process from now on!

**Comment by paskyorg** [comment]
Thanks hubo1016. I will try it.

Great Lukasa. Very good news!

**Comment by Psykar** [comment]
Appears that there's no linux 3.6 wheel yet?

**Comment by Lukasa** [comment]
Sounds about right. I'll fix that up sometime in the next few days.

**Comment by Lukasa** [comment]
Ok, cool, I've resolved that. Sorry I missed it: that's the problem with partial wheel work!
